import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "@/modules/shared/provider";
import type { PropsWithChildren } from "react";
import { Toaster } from "@/components/ui/sonner";

const pjs = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-pjs",
  preload: true,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Posaha",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body className={pjs.variable}>
        <Provider>
          {props.children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
