import { ProgressBar } from '@/components/ui/progress-bar'
import { Toaster } from '@/components/ui/sonner'

import { Provider } from '@/modules/shared/provider'

import './globals.css'

import type { Metadata } from 'next'
import PlusJakartaSansLocal from 'next/font/local'
import type { PropsWithChildren } from 'react'

const pjs = PlusJakartaSansLocal({
  src: [
    {
      path: '../../public/fonts/PlusJakartaSans/PlusJakartaSans-Normal-Variable.ttf',
      style: 'normal',
      weight: 'normal',
    },
    {
      path: '../../public/fonts/PlusJakartaSans/PlusJakartaSans-Italic-Variable.ttf',
      style: 'italic',
      weight: 'normal',
    },
  ],
  variable: '--font-pjs',
  preload: true,
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Posaha',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang='id' suppressHydrationWarning>
      <body className={pjs.variable}>
        <Provider>
          {props.children}
          <Toaster />
          <ProgressBar />
        </Provider>
      </body>
    </html>
  )
}
